apiVersion: v1
kind: Template
metadata:
  name: jenkins-master-s2i
labels:
  template: jenkins-master-s2i
metadata:
  annotations:
    openshift.io/display-name: Jenkins Master (S2I)
    description: Creates a Jenkins master using S2I for installing plugins and configuring Jenkins
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-master-s2i
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: "1Gi"
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: "1Gi"
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: "jenkins"
- description: The name of the service used for master/slave communication.
  displayName: Jenkins JNLP Service Name
  name: JNLP_SERVICE_NAME
  value: "jenkins-jnlp"
- description: Whether to enable OAuth OpenShift integration. If false, the static account 'admin' will be initialized with the password 'password'.
  displayName: Enable OAuth in Jenkins
  name: ENABLE_OAUTH
  value: "true"
- description: Name of the ImageStreamTag to be used for the Jenkins image.
  displayName: Jenkins Image to use (format: [image]:[tag])
  name: JENKINS_IMAGE
  value: "registry.devapps.c3ms.org/custom-jenkins/custom-jenkins:latest"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${JENKINS_SERVICE_NAME}
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"${JENKINS_SERVICE_NAME}\"}}"
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: ${JENKINS_SERVICE_NAME}_edit
  groupNames: null
  subjects:
  - kind: ServiceAccount
    name: ${JENKINS_SERVICE_NAME}
  roleRef:
    name: edit
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins
    name: ${JENKINS_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: ${JENKINS_SERVICE_NAME}
      deploymentconfig: ${JENKINS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins
    name: ${JNLP_SERVICE_NAME}
  spec:
    ports:
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: ${JENKINS_SERVICE_NAME}
      deploymentconfig: ${JENKINS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${JENKINS_SERVICE_NAME}
    name: ${JENKINS_SERVICE_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${JENKINS_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${JENKINS_SERVICE_NAME}
    name: ${JENKINS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${JENKINS_SERVICE_NAME}
      deploymentconfig: ${JENKINS_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${JENKINS_SERVICE_NAME}
          deploymentconfig: ${JENKINS_SERVICE_NAME}
      spec:
        containers:
        - volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
          env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: ${ENABLE_OAUTH}
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_MASTER
            value: "https://kubernetes.default:443"
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JNLP_SERVICE_NAME
            value: ${JNLP_SERVICE_NAME}
          - name: INSTALL_PLUGINS
            value: >-
              pipeline-utility-steps:2.1.0,branch-api:2.0.20,blueocean-pipeline-api-impl:1.10.2,antisamy-markup-formatter:2.0,jquery-detached:1.2.1,blueocean-dashboard:1.10.2,scm-api:2.2.8,external-monitor-job:1.7,authentication-tokens:1.3,bouncycastle-api:2.17,analysis-model-api:5.2.0,kubernetes-credentials:0.3.0,mailer:1.21,workflow-basic-steps:2.11,config-file-provider:3.5,blueocean:1.10.2,warnings-ng:5.3.0,handlebars:1.1,pipeline-model-declarative-agent:1.1.1,pipeline-stage-step:2.3,git:3.9.3,workflow-scm-step:2.6,zentimestamp:4.2,favorite:2.3.1,blueocean-display-url:2.2.0,ldap:1.20,ssh-agent:1.19,pipeline-model-definition:1.3.4.1,pipeline-milestone-step:1.3.1,matrix-project:1.14,workflow-step-api:2.20,mapdb-api:1.0.9.0,pipeline-model-api:1.3.4.1,m2release:0.16.2,github-api:1.90,sse-gateway:1.16,workflow-durable-task-step:2.26,pipeline-rest-api:2.10,blueocean-bitbucket-pipeline:1.10.2,variant:1.1,durable-task:1.26,workflow-api:2.34,workflow-multibranch:2.20,pipeline-stage-view:2.10,pipeline-stage-tags-metadata:1.3.4.1,ant:1.9,display-url-api:2.2.0,blueocean-git-pipeline:1.10.2,blueocean-rest:1.10.2,pipeline-model-extensions:1.3.4.1,ssh-slaves:1.30.0,build-timestamp:1.0.3,jackson2-api:2.9.9.1,thinBackup:1.9,template-project:1.5.2,windows-slaves:1.4,lockable-resources:2.3,jira:3.0.5,workflow-support:3.3,credentials-binding:1.15,junit:1.24,subversion:2.10.3,cloudbees-devoptics-enabler:0.4,git-server:1.7,workflow-cps-global-lib:2.11,run-condition:0.10,openshift-client:1.0.16,javadoc:1.5,apache-httpcomponents-client-4-api:4.5.5-3.0,pipeline-github-lib:1.0,parameterized-trigger:2.35.2,maven-plugin:3.6,workflow-job:2.33,job-dsl:1.68,blueocean-pipeline-scm-api:1.10.2,jsch:0.1.55.1,pam-auth:1.5.1,pipeline-input-step:2.8,matrix-auth:2.2,extra-columns:1.20,fortify-on-demand-uploader:5.0.0,structs:1.20,mercurial:2.3,credentials:2.3.7,handy-uri-templates-2-api:2.1.6-1.0,blueocean-pipeline-editor:1.10.2,blueocean-github-pipeline:1.10.2,docker-commons:1.11,fortify:19.2.30,htmlpublisher:1.16,kubernetes:1.12.8,workflow-cps:2.72,pipeline-build-step:2.7,script-security:1.61,github-branch-source:2.3.6,ruby-runtime:0.12,blueocean-events:1.10.2,cloudbees-folder:6.6,devoptics:1.1863,token-macro:2.6,jdk-tool:1.2,conditional-buildstep:1.3.1,configuration-as-code:1.36,gitlab-hook:1.4.2,slack:2.27,gitlab-plugin:1.5.13,plain-credentials:1.5,github-organization-folder:1.6,pipeline-graph-analysis:1.7,ssh-credentials:1.17.1,blueocean-core-js:1.10.2,blueocean-i18n:1.10.2,openshift-login:1.0.15,docker-workflow:1.14,git-client:2.7.3,blueocean-jwt:1.10.2,blueocean-autofavorite:1.2.2,timestamper:1.9,blueocean-jira:1.10.2,view-job-filters:2.1.1,workflow-aggregator:2.6,jobConfigHistory:2.24,workflow-remote-loader:1.4,blueocean-config:1.10.2,metrics:4.0.2.6,jenkins-design-language:1.10.2,clover:4.10.0,blueocean-commons:1.10.2,openshift-pipeline:1.0.55,command-launcher:1.3,blueocean-web:1.10.2,cloudbees-bitbucket-branch-source:2.2.15,ace-editor:1.0.1,momentjs:1.1,pubsub-light:1.12,blueocean-personalization:1.10.2,github:1.29.2,blueocean-rest-impl:1.10.2,openshift-sync:1.0.27
          image: ${JENKINS_IMAGE}
          imagePullPolicy: Always
          name: ${JENKINS_SERVICE_NAME}
          resources: {}
          terminationMessagePath: /dev/termination-log
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: ${JENKINS_SERVICE_NAME}
        volumes:
        - name: jenkins-data
          emptyDir: {}
